# Generated by Django 2.1.1 on 2018-09-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20180906_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='amount',
            new_name='predicted',
        ),
        migrations.AddField(
            model_name='shift',
            name='actual',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
