# Generated by Django 2.1.1 on 2018-09-07 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20180907_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
